# Generated by Django 4.1.4 on 2023-01-03 22:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="id",
        ),
        migrations.AddField(
            model_name="notification",
            name="notification_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
