# Generated by Django 4.1.3 on 2022-11-13 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="active",
            new_name="approve",
        ),
    ]
