# Generated by Django 4.0 on 2023-04-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_comment_approve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilesettings',
            name='image',
            field=models.FileField(blank=True, default=None, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='profilesettings',
            name='linkedin_url',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profilesettings',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='profilesettings',
            name='twitter_url',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profilesettings',
            name='website_url',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
