# Generated by Django 4.1.4 on 2023-01-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_notification_id_notification_notification_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="slug",
            field=models.SlugField(auto_created=True, blank=True, max_length=255),
        ),
    ]
