# Generated by Django 4.0 on 2023-03-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_profilesettings_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilesettings',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
