# Generated by Django 4.1.3 on 2022-11-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_rename_active_comment_approve"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="like",
            field=models.IntegerField(default=0),
        ),
    ]
