# Generated by Django 4.1.4 on 2023-01-05 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_rename_slug_notification_post_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="post_slug",
        ),
    ]
