# Generated by Django 4.0 on 2023-03-02 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_profilesettings_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilesettings',
            old_name='profile_image',
            new_name='image',
        ),
    ]
