# Generated by Django 4.0 on 2023-03-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_profile_image_profilesettings_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilesettings',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
