# Generated by Django 4.1.3 on 2022-11-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_post_like"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="like",
        ),
        migrations.AddField(
            model_name="post",
            name="like",
            field=models.IntegerField(default=0),
        ),
    ]
