# Generated by Django 4.0 on 2023-03-12 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_profilesettings_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilesettings',
            old_name='linked_in_url',
            new_name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='profilesettings',
            name='instagram_url',
        ),
    ]
