# Generated by Django 4.1.3 on 2022-11-26 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0015_alter_post_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="post_image",
            new_name="image",
        ),
    ]
