# Generated by Django 4.1.3 on 2022-12-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0024_alter_post_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="pub_date",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
