# Generated by Django 4.1.3 on 2022-12-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0026_user_alter_comment_user_alter_post_like_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(
                default="", max_length=255, unique=True, verbose_name="email"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="staff",
            field=models.BooleanField(default=False),
        ),
    ]
