# Generated by Django 4.1.3 on 2022-12-10 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0029_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
