# Generated by Django 4.1.3 on 2022-12-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0035_userdetails_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="location",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
