# Generated by Django 4.1.3 on 2022-12-11 17:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0036_alter_userdetails_location"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserDetails",
            new_name="ProfileSettings",
        ),
    ]
