# Generated by Django 4.1.3 on 2022-12-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0038_alter_profilesettings_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilesettings",
            name="instagram_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profilesettings",
            name="linked_in_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profilesettings",
            name="twitter_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profilesettings",
            name="website_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
